/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    clipPath: {
      polygon: 'polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)',
    },
  },
  daisyui: {
    themes: [
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
      'dim',
      'nord',
      'sunset',
      'royal',
      'ocean',
      'wine',
      'mirage',
      'neon',
      'contrast',
      'flat',
      'facebook',
      'modern',
      'purple',
      'twitter'],
  },
  plugins: [require('daisyui')],
}

